### ISSUE TITLE
User Story : User Login Page

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Band-Grooves#1]
As a User I want  to be able to login and create and account so that I can enjoy the features of the web site.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [ ] <label><input type="checkbox" disabled /> Task 1 : Install Allauth</label>
- [ ] <label><input type="checkbox" disabled /> Task 2 : Compose a Login page</label>
- [ ] <label><input type="checkbox" disabled /> Task 3 :  Document Login Page</label>

## Acceptance Criteria :
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :   Page Displays on Site</label>
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :   User Can Create Account</label>
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :  Can bee seen in Django admin Panel </label>
