### ISSUE TITLE
User Story : Authentication and Authorization

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Band-Grooves#2]
As an administrator, I want to implement security measures, including user authentication and authorization, to protect the website and its content.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [x] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [ ] <label><input type="checkbox" disabled /> Task 1 : Install Allauth</label>
- [ ] <label><input type="checkbox" disabled /> Task 2 : Populate Allauth Directory</label>
- [ ] <label><input type="checkbox" disabled /> Task 3 : Add Restrictions to Nav Bar</label>

## Acceptance Criteria :
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :  Login Logout functions</label>
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :  Login Superuser\User restrictions apply  </label>
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :  Heroko : Login Superuser\User restrictions apply  </label>
